### ISSUE TITLE
입력 관련 문제

### ISSUE THREAD

**Issue by K-Minhyeok** [Gogumalang/OSSL_Big_Project#14]
입력을 받을 때, 음바페 같은 경우에 Mbappé로 뒤에 e가 위에 뭐 붙어있는 채로 있는데
입력받을 때 그냥 e랑 é를 다른 걸로 인식할까요?

**Comment by Gogumalang** [comment]
é 를 e로 바꿀 수 있으면 좋을 것 같습니다! 

추가로, 파일 가장 위에 첫줄(LABEL-1	이름	포지션	가격)은 제외해주시고
1	Kylian Mbappé	Centre-Forward	€180.00m 
중에서 '1' 과 유로 표시와 m표시도 없애주실 수 있으시면 감사하겠습니다!

**Comment by K-Minhyeok** [comment]
해결했습니다 ! 
:)
