### ISSUE TITLE
README - 첫 번째 줄 충돌 (해결 안 됨)

### ISSUE THREAD

**Issue by K-Minhyeok** [Gogumalang/OSSL_Big_Project#2]
줄을 한 칸 띄웠는데도 계속 충돌이 난다고 뜨는 것 같습니다.
Merge 하실 때도 뜨면, 다른 줄에 옮기고 없어졌다고 이슈 내주시면 감사하겠습니다.

**Comment by Gogumalang** [comment]
PR 받았을 때 충돌 뜨지는 않았습니다!
