### ISSUE TITLE
README 내용이랑 WIKI 내용 바뀜  / contributor 로 등록

### ISSUE THREAD

**Issue by K-Minhyeok** [Gogumalang/OSSL_Big_Project#3]
제가 올린 README FILE에 있는 내용이 WIKI로 가야하는데 
원본 repo에서 WIKI가 안 보여서 올릴 수가 없네요!

제가 contributor로 등록이 되어야하는 것 같은데 한 번 확인 부탁드립니다!

**Comment by K-Minhyeok** [comment]
제 거 PR받아주시면 등록된다네요!!

**Comment by Gogumalang** [comment]
넵 PR 받았습니다!
