### ISSUE TITLE
Login info 비교 구현 미완성

### ISSUE THREAD

**Issue by K-Minhyeok** [Gogumalang/OSSL_Big_Project#5]
아직 login 할 때 ID PW비교하는 함수는 구현 안 했습니다.

그리고 로그인 했을 때, 로그인한 해당 유저에게 선수가 뜨게 하는 게 가능한지 한 번 생각해보겠습니다.

시간나실 때 Login_info.c 파일 확인부탁드립니다. :)

**Comment by Gogumalang** [comment]
파일 확인해보니까 txt file의 내용을 모두 구조체에 넣고 구조체의 내용을 바탕으로 비교하셨더라고요, 
그것도 괜찮은 방법인데, file 함수를 적절히 사용하면 file을 읽으면서 ID를 찾을 수 있어서 그런 방식으로 구현해보시는건 어떨까요? 
예로 들어서 fopen("텍스트파일","r") 로 열고, while(!feof ) // 파일이 끝날 때까지 반복하다가
만약 찾고자 하는 id랑 같은 이름의 파일 속 문자열이 발견되었으면, pw도 확인해보고, 일치하면 로그인이 되는 방식. 

정확히 이해가 되지 않았으면 제가 예시 코드 첨부해 보내드리겠습니다!

**Comment by K-Minhyeok** [comment]
참고하고 만들었습니다 fscanf를 생각 못했네요 감사합니다! 
:)
