### ISSUE TITLE
크롤링에 관하여

### ISSUE THREAD

**Issue by K-Minhyeok** [Gogumalang/OSSL_Big_Project#8]
이래저래 찾아보니까 'C에서 크롤링이 가능은 하다' 고 합니다.
근데 열 줄정도면 끝날 게 200,300줄까지 간다고해서 이 점은 한 번 조율을 해봐야 할 듯합니다.

**Comment by Gogumalang** [comment]
'10줄 정도면 끝나는 것'이란 말은 C언어로 구현하지 않고 다른 언어로 크롤링 했을 때 인가요? 
C언어로 크롤링을 할 수는 있지만 복잡하다는 말씀 맞죠?
